name: event-loop autotests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linter:
    if: |
      github.ref == 'refs/heads/main' ||
      github.head_ref == 'feature/event-loop'
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      # Downloads a copy of the code in your repository before running code quality test
      - name: Checkout code
        uses: actions/checkout@v4
      #Starts flake8 linter
      - name: Test code quality
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pep8-naming flake8-broken-line flake8-return
          cd ./event-loop
          python -m flake8

  tests:
    if: |
      github.ref == 'refs/heads/main' ||
      github.head_ref == 'feature/event-loop'
    runs-on: ubuntu-latest
    needs: [ linter ]
    container: python:3.12
    steps:
    # Downloads a copy of the code in your repository before running CI tests
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Test code functionality
      run: |
        pip install pytest==8.3.2
        cd ./event-loop
        pytest

  control-code:
    if: |
      github.ref == 'refs/heads/main' ||
      github.head_ref == 'feature/event-loop'
    name: control-code
    needs: [ tests ]
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
      # Downloads a copy of the code in your repository before running code quality test
      - name: Checkout code
        uses: actions/checkout@v4
      #Starts sqlfluff linter
      - name: Check Workflow Status
        run: |
          ./.github/workflows/code_generator -t ./event-loop/tests